baseurl = "/"
languageCode = "en-us"
title = "Camunda Team Blog"
theme = "blogcamundaorg"
preservetaxonomynames = true
# uglyurls = true


# [taxonomies]
#   tag = "tags"
#   category = "categories"
#   author = "authors"

# pagination setup
# http://gohugo.io/extras/pagination/
Paginate = 5


[params]
  repo = "camunda/blog.camunda.org"
  gaCode = "UA-39060941-1"
  disqusShortname = "camundablog"
  gSearchApiKey= "AIzaSyCMGfdDaSfjqv5zYoS0mTJnOT3e9MURWkU"
  gSearchCtx= "007121298374582869478:-vzd0u36nki"
